version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=DogBreedsDb;User Id=sa;Password=YourPassword;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest # lub '2019-latest'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword
    ports:
      - "1433:1433"
